### ISSUE TITLE
Compilation fails on simple examples

### ISSUE THREAD

**Issue by naasking** [ltrzesniewski/RazorBlade#15] opened 2024-12-04 14:02 UTC
Trying RazorBlade 0.6.0 and can't seem to compile even a simple example called Basic.cshtml, like:

````html
@inherits RazorBlade.HtmlTemplate<int>
<button>@Model</button>
````

This fails with:

`1>C:\repos\SqsRB\SqsRB\obj\Debug\net9.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Basic_cshtml.g.cs(32,67,32,79): error CS0507: 'Basic.ExecuteAsync()': cannot change access modifiers when overriding 'protected internal' inherited member 'RazorTemplate.ExecuteAsync()'
1>C:\repos\SqsRB\SqsRB\obj\Debug\net9.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Basic_cshtml.g.cs(65,80,65,84): warning CS0108: 'Basic.Html' hides inherited member 'HtmlTemplate.Html'. Use the new keyword if hiding was intended.`

I haven't added any other code, it's just the standard minimal APIs project template, and then I added Basic.cshtml. I also tried a template with an explicit Model property and that didn't work either, same issue.

**Comment by ltrzesniewski** [comment] 2024-12-04 16:04
`Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator` is not provided by RazorBlade. I suspect you're using ASP.NET, and this is probably a duplicate of #14. Can you confirm this?

I've added the following warning, but did not release the change yet, oops 🤦 

> RazorBlade shouldn't be used in ASP.NET projects, as several Razor source generators would process the same .cshtml files by default. ASP.NET's generator is not compatible with the RazorBlade library.

You can work around this by moving the templates you'd like to use with RazorBlade to a separate project, or by using ASP.NET to process the templates.

**Comment by naasking** [comment] 2024-12-04 16:18
You are correct, this is an ASP.NET minimal APIs project but I didn't add razor controllers or pages, so it's a little annoying that Microsoft pulled in all of those dependencies regardless. Oh well.

Putting the templates in a separate project does let that project build, however the generated templates are not accessible out of the box to other projects because they're generated as internal classes:

![image](https://github.com/user-attachments/assets/31e972e5-8de0-4cb3-bba4-6f5b231a3357)

Obviously I could create some a static class with constructor methods to return the templates, but I'd rather not have to if there's a simpler way to make them public by default.

**Comment by ltrzesniewski** [comment] 2024-12-04 16:35
Ok, thanks for the confirmation. I'll release a new version containing the warning and document this, as the error is very confusing.

RazorBlade generates internal classes, but you can use `[assembly: InternalsVisibleTo(...)]` in order to make them visible to your ASP.NET project easily.

**Comment by naasking** [comment] 2024-12-04 17:00
Weird, I just tried adding a second .cshtml file to the templates project and now codegen doesn't seem to work at all, no classes are generated in the template .dll. Adding a static class to that project to construct instances generates build errors that the type or namespace can't be found.

**Comment by ltrzesniewski** [comment] 2024-12-04 17:06
Weird indeed. Maybe make sure VS didn't alter the csproj file contents.

**Comment by naasking** [comment] 2024-12-04 17:07
I think the issue is that even if the templates are in a separate project, if it's linked to an ASP.NET project, then there's confusion about who generates the templates. When I create a static class that constructs template instances, VS 2022 automatically adds  `using AspNetCoreGeneratedDocument;` to the top of the file, which is the namespace under which the Button class is placed, but nothing actually gets generated and I don't think this is what it was doing before, and so I believe it might be using the wrong generator.

I tried creating a second class library and adding the templates back one at a time, same issue. Perhaps you have some thoughts.

**Comment by ltrzesniewski** [comment] 2024-12-04 17:13
Hmm I haven't tried this, but maybe try adding this to your class library csproj:

```xml
<PropertyGroup>
  <UsingMicrosoftNETSdkRazor>false</UsingMicrosoftNETSdkRazor>
</PropertyGroup>
```

**Comment by ltrzesniewski** [comment] 2024-12-04 17:24
Or just make sure you're not using the Web SDK. You should use the `Microsoft.NET.Sdk` in your project file:

```xml
<Project Sdk="Microsoft.NET.Sdk">
```

**Comment by naasking** [comment] 2024-12-04 17:29
Ok, I just created a fresh standalone project and what happens is that every time I add a .cshtml file it removes it in the .csproj file:
````
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <RazorBlade Remove="Button.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="RazorBlade" Version="0.6.0" />
  </ItemGroup>

</Project>
````
If I remove the lines for `<RazorBlade Remove="Button.cshtml" />` then it builds correctly and works as expected.

The build action was also not set correctly, sometimes getting set to Content, sometimes to C# analyzer file:
![image](https://github.com/user-attachments/assets/65dd8b17-51b7-496d-85dc-257405af9826)

After removing the lines that remove Button.cshtml and ensuring RazorBlade is set as the build action (which adds the .cshtml as additional files to the csproj), everything seems to be fine again.

**Comment by ltrzesniewski** [comment] 2024-12-04 17:33
Ok, thanks for reporting this (I use Rider so I didn't notice the issue in VS). I'll see what I can do about it.

**Closed as completed** 2024-12-04 17:32 UTC
Labels: duplicate

**Comment by naasking** [comment] 2024-12-18 16:28
> RazorBlade generates internal classes, but you can use `[assembly: InternalsVisibleTo(...)]` in order to make them visible to your ASP.NET project easily.

So the only issue is that this prevents creating a project with a set of reusable templates. For any new project you'd have to modify the source of the template project to add this attribute. Is there any way to have the generator create public templates?

**Comment by ltrzesniewski** [comment] 2024-12-18 19:38
Ok I see. I can add an option, see #19.
